// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp3jC3ZV5RgeOvbJKXVWlJXSh7bIfWD0g',
    appId: '1:1026165424656:web:8f2091823e653ef1134095',
    messagingSenderId: '1026165424656',
    projectId: 'htn2023-5918e',
    authDomain: 'htn2023-5918e.firebaseapp.com',
    databaseURL: 'https://htn2023-5918e-default-rtdb.firebaseio.com',
    storageBucket: 'htn2023-5918e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLxxf1cpImADpcC3ILaNklWecIjunD2cc',
    appId: '1:1026165424656:android:98a48f75a6abc9fd134095',
    messagingSenderId: '1026165424656',
    projectId: 'htn2023-5918e',
    databaseURL: 'https://htn2023-5918e-default-rtdb.firebaseio.com',
    storageBucket: 'htn2023-5918e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9NZBp26KYmt4nt6c8c8YBlyAo5isSbA',
    appId: '1:1026165424656:ios:4dc81e6722224974134095',
    messagingSenderId: '1026165424656',
    projectId: 'htn2023-5918e',
    databaseURL: 'https://htn2023-5918e-default-rtdb.firebaseio.com',
    storageBucket: 'htn2023-5918e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9NZBp26KYmt4nt6c8c8YBlyAo5isSbA',
    appId: '1:1026165424656:ios:d741291725e3dbb5134095',
    messagingSenderId: '1026165424656',
    projectId: 'htn2023-5918e',
    databaseURL: 'https://htn2023-5918e-default-rtdb.firebaseio.com',
    storageBucket: 'htn2023-5918e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
